config/routes.rb
resources :projects do
  get '/issuestats', :to => 'issuestats#index', as: 'issuestats'
  post '/issuestats', :to => 'issuestats#show', as: 'issuestats_show'
end

app/models/issue_start_time.rb
class IssueStartTime < ActiveRecord::Base
  unloadable
  validates :start_datetime, :issue_id, presence: true
end

app/controllers/issuestats_controller.rb
class IssuestatsController < ApplicationController
  unloadable
  before_filter :find_project_by_project_id ,:authorize

  def index
    @project = Project.find(params[:project_id])
    @issues = Issue.where(:project_id => @project.id)

    @status_ids = Array.new
    @issues.each do |issue|
      unless @status_ids.include?(issue.status_id)
         @status_ids << issue.status_id
      end
    end

    @options = Array.new
    @status_ids.each do |status_id|
      issue_status = IssueStatus.find_by_id(status_id)
      @options.push([issue_status.name, status_id])
    end

  end

  def show
    @start_date = Date.parse(params[:issuestats][:start_date])
    @end_date = Date.parse(params[:issuestats][:end_date])
    @intervention_status = params[:issuestats][:intervention_status]
    @intervention_statusname = IssueStatus.find_by_id(params[:issuestats][:intervention_status]).name
    @intervention_time = params[:issuestats][:intervention_time]
    @resolve_status = params[:issuestats][:resolve_status]
    @resolve_statusname = IssueStatus.find_by_id(params[:issuestats][:resolve_status]).name
    @resolve_time = params[:issuestats][:resolve_time]

    @project = Project.find(params[:project_id])
    @issues = Issue.where(:project_id => @project.id, :start_date => @start_date..@end_date)
    if @issues.length == 0
      flash[:error] = l(:issuestats_not_find)
      redirect_to project_issuestats_path(:project_id => @project.id)
    else
      @trackers = @project.rolled_up_trackers
      @priorities = IssuePriority.where(:active => true)

      @status_ids = Array.new
      @issues.each do |issue|
        unless @status_ids.include?(issue.status_id)
           @status_ids << issue.status_id
        end
      end
    end
  end

end

app/helpers/issuestats_helper.rb
module IssuestatsHelper
  def get_issue_intervention_time (issue, intervention_status)
    issue_start_time = IssueStartTime.find_by_issue_id(issue.id)
    if issue_start_time != nil
      start_datetime = issue_start_time.start_datetime
    else
      if (issue.start_date.year == issue.created_on.year &&
          issue.start_date.month == issue.created_on.month &&
          issue.start_date.day == issue.created_on.day)
        start_datetime = issue.created_on
      else
        start_datetime = DateTime.new(issue.start_date.year, issue.start_date.month, issue.start_date.day)
      end
    end

    @journals = Journal.where(journalized_id: issue.id).order("created_on ASC")
    intervention_time = -1;

    @journals.each do |journal|
      action_datetime = journal.created_on
      jdetails = JournalDetail.where(journal_id: journal.id)

      jdetails.each do |jdetail|
        if jdetail.property == 'attr' && jdetail.prop_key == 'status_id' && jdetail.value == intervention_status
          intervention_time = ((action_datetime - start_datetime)/60).to_i
          break
        end
      end

      if intervention_time != -1
        break
      end
    end

    if intervention_time >= 0
      return intervention_time
    else
      return (-1)
    end
  end

  def get_issue_resolve_time (issue, intervention_status, resolve_status)
    @journals = Journal.where(journalized_id: issue.id).order("created_on ASC")
    first_intervene_time = -1

    @journals.each do |journal|
      action_datetime = journal.created_on
      jdetails = JournalDetail.where(journal_id: journal.id)

      if issue.status_id.to_i == intervention_status.to_i
        return (-1)
      end

      jdetails.each do |jdetail|
        if jdetail.property == 'attr' && jdetail.prop_key == 'status_id' && jdetail.value == intervention_status
          first_intervene_time = action_datetime
          break
        end
      end

      if first_intervene_time != -1
        break
      end
    end

    @journals = Journal.where(journalized_id: issue.id).order("created_on DESC")
    resolve_time = -1

    @journals.each do |journal|
      action_datetime = journal.created_on
      jdetails = JournalDetail.where(journal_id: journal.id)

      jdetails.each do |jdetail|
        if jdetail.property == 'attr' && jdetail.prop_key == 'status_id' && jdetail.value == resolve_status && first_intervene_time != -1
          resolve_time = ((action_datetime - first_intervene_time)/60).to_i
          break
        end
      end

      if resolve_time != -1
        break
      end
    end

    if resolve_time >= 0
      return resolve_time
    else
      return (-1)
    end
  end

  def get_time_statistics (issues, intervention_time, resolve_time, intervention_status, resolve_status)
    expired_intervention_count = 0
    nonexpired_intervention_count = 0
    expired_resolve_count = 0
    nonexpired_resolve_count = 0
    not_intervene_count = 0
    not_resolve_count = 0

    issues.each do |issue|
      int_time = get_issue_intervention_time(issue, intervention_status)
      res_time = get_issue_resolve_time(issue, intervention_status, resolve_status)

      if (int_time == (-1))
        not_intervene_count += 1
      elsif (int_time > intervention_time.to_i)
        expired_intervention_count += 1
      else
        nonexpired_intervention_count += 1
      end

      if (res_time == (-1))
        not_resolve_count += 1
      elsif (res_time > resolve_time.to_i)
        expired_resolve_count += 1
      else
        nonexpired_resolve_count += 1
      end
    end

    results = Array.new
    results.push(l(:issuestats_expired_int) + expired_intervention_count.to_s)
    results.push(l(:issuestats_expired_res) + expired_resolve_count.to_s)
    results.push(l(:issuestats_not_expired_int) + nonexpired_intervention_count.to_s)
    results.push(l(:issuestats_not_expired_res) + nonexpired_resolve_count.to_s)
    results.push(l(:issuestats_not_intervened_label) + not_intervene_count.to_s)
    results.push(l(:issuestats_not_resolved_label) + not_resolve_count.to_s)

    return results
  end

  def get_time_averages (issues, intervention_time, resolve_time, intervention_status, resolve_status)
    sum_intervention_time = 0.0
    count_intervened_issue = 0
    avg_intervention_time = 0.0

    sum_resolve_time = 0.0
    count_resolved_issue = 0
    avg_resolve_time = 0.0

    issues.each do |issue|
      int_time = get_issue_intervention_time(issue, intervention_status)
      res_time = get_issue_resolve_time(issue, intervention_status, resolve_status)

      if (int_time != (-1))
        count_intervened_issue += 1
        sum_intervention_time += int_time
      end

      if (res_time != (-1))
        count_resolved_issue += 1
        sum_resolve_time += res_time
      end
    end

    avg_intervention_time = sum_intervention_time / count_intervened_issue
    avg_resolve_time = sum_resolve_time / count_resolved_issue

    results = Array.new
    results.push(l(:issuestats_avg_int_time) + avg_intervention_time.round(1).to_s)
    results.push(l(:issuestats_avg_res_time) + avg_resolve_time.round(1).to_s)

    return results
  end

end

app/views/issuestats/_issues_add_start_datetime.html.erb
<% if @project.module_enabled?("issuestats") == true %>
  <% @issue_start_time = IssueStartTime.find_by_issue_id(params[:id]) %>
  <% if @issue_start_time != nil %>
    <% time = Time.parse(@issue_start_time.start_datetime.to_s).utc.localtime %>
  <% else %>
    <% time = Time.now.utc.localtime %>
  <% end %>
  <p>
    <% time.to_formatted_s(:time) %>
    <%= label :issuestats, l(:issue_start_time) %>
    <%= time_field(:issuestats, :start_time, :value => time.to_s(:time), :required => true) %>
  </p>
<% end %>

app/views/issuestats/_issues_show_start_datetime.html.erb
<% if @project.module_enabled?("issuestats") == true %>
  <% @issue_start_time = IssueStartTime.find_by_issue_id(params[:id]) %>
  <% if @issue_start_time != nil %>
    <div class="splitcontentleft">
      <div class="start-date attribute">
        <div class="label">
          <%= l(:issue_start_time) + ":" %>
        </div>
        <div class="value">
          <%= Time.parse(@issue_start_time.start_datetime.to_s).utc.localtime.strftime("%m/%d/%Y %I:%M %p") %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/issuestats/index.html.erb
<h1><%= l(:issuestats_title)%></h1>

<table>
  <%= form_for :issuestats, url: project_issuestats_show_path(@project) do |f| %>
    <tr><p><td><%= f.label l(:issuestats_start_date) %></td><td> <%= f.text_field :start_date, :type => "date", :required => true %> ,  <%= f.text_field :end_date, :type => "date", :required => true %> </td></p></tr>
    <tr><p><td><%= f.label l(:issuestats_intervention_status) %></td><td> <%= select :issuestats, :intervention_status, options_for_select(@options), {:include_blank => l(:issuestats_select_one)}, {:multiple => false, :required => true} %></td></p></tr>
    <tr><p><td><%= f.label l(:issuestats_intervention_time_min) %></td><td> <%= f.text_field :intervention_time, :type => "number", :required => true %></td></p></tr>
    <tr><p><td><%= f.label l(:issuestats_resolve_status) %></td><td> <%= select :issuestats, :resolve_status, options_for_select(@options), {:include_blank => l(:issuestats_select_one)}, {:multiple => false, :required => true} %></td></p></tr>
    <tr><p><td><%= f.label l(:issuestats_resolve_time_min) %></td><td> <%= f.text_field :resolve_time, :type => "number", :required => true %></td></p></tr>
    <tr><td><%= f.submit l(:issuestats_show_stats) %></td><td></td></tr>
  <% end %>
</table>

<div class="issuestats_notes">
  <p>
    <%= l(:issuestats_notes) %><br>
    <%= l(:issuestats_intervention_time) %><%= l(:issuestats_intervention_desc) %><br>
    <%= l(:issuestats_resolve_time) %><%= l(:issuestats_resolve_desc) %>
  </p>
</div>

app/views/issuestats/show.html.erb
<h1><%= l(:issuestats_title)%></h1>

<div class="issuestats_info">
  <p>
    <%= l(:issuestats_info_between) %> <b><%= params[:issuestats][:start_date] %></b> , <b><%= params[:issuestats][:end_date] %></b><br>
    <%= l(:issuestats_intervention_status) %> <b><%= @intervention_statusname %></b>
    <%= l(:issuestats_intervention_time_min) %> <b><%= @intervention_time %></b><br>
    <%= l(:issuestats_resolve_status) %> <b><%= @resolve_statusname %></b>
    <%= l(:issuestats_resolve_time_min) %> <b><%= @resolve_time %></b><br>
  </p>
</div>


<h2><%= l(:issuestats_trackers_vs_statuses) %></h2>

<table border="1" width="100%">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th colspan=<%= @status_ids.length+1%>><%= l(:issuestats_title_statuses) %></th>
    </tr>

    <tr>
      <th></th>
      <th></th>
      <% @status_ids.each do |status_id| %>
        <th>
          <%= IssueStatus.find_by_id(status_id) %>
        </th>
      <% end %>
      <th><%= l(:issuestats_all_statuses) %></th>
    </tr>
  </thead>

  <tr>
    <th rowspan=<%= @trackers.length+2%>><%= l(:issuestats_title_trackers) %></th>
    <% @trackers.each do |tracker| %>
      <tr>
        <th><%= tracker.name %></th>
        <% @status_ids.each do |status_id| %>
          <td>
            <% @priorities.each do |priority| %>
              <%= priority.name %>: <%= @issues.where(:tracker_id => tracker.id).where(:status_id => status_id).where(:priority_id => priority.id).length %>
              <br>
            <% end %>
          </td>
        <% end %>
        <td>
          <% @priorities.each do |priority| %>
            <%= priority.name %>: <%= @issues.where(:tracker_id => tracker.id).where(:priority_id => priority.id).length %>
            <br>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <th><%= l(:issuestats_all_trackers) %></th>
      <% @status_ids.each do |status_id| %>
        <td>
          <% @priorities.each do |priority| %>
            <%= priority.name %>: <%= @issues.where(:status_id => status_id).where(:priority_id => priority.id).length %>
            <br>
          <% end %>
        </td>
      <% end %>
      <td>
        <% @priorities.each do |priority| %>
          <%= priority.name %>: <%= @issues.where(:priority_id => priority.id).length %>
          <br>
        <% end %>
      </td>
    </tr>
  </tr>
</table>

<br>
<h2><%= l(:issuestats_time_analyze_trackers_priorities) %></h2>

<table border="1" width="100%">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th colspan=<%= @priorities.length+1%>><%= l(:issuestats_title_priorities) %></th>
    </tr>

    <tr>
      <th></th>
      <th></th>
      <% @priorities.each do |priority| %>
        <th>
          <%= priority %>
        </th>
      <% end %>
      <th><%= l(:issuestats_all_priorities) %></th>
      <th><%= l(:issuestats_average_min) %></th>
    </tr>
  </thead>

  <tr>
    <th rowspan=<%= @trackers.length+2%>><%= l(:issuestats_title_trackers) %></th>
    <% @trackers.each do |tracker| %>
      <tr>
        <th><%= tracker.name %></th>
        <% @priorities.each do |priority| %>
          <td>
            <% issues_t_p = @issues.where(:tracker_id => tracker.id).where(:priority_id => priority.id) %>
            <% results = get_time_statistics(issues_t_p, @intervention_time, @resolve_time, @intervention_status, @resolve_status) %>
            <% results.each do |result| %>
              <%= result %><br>
            <% end %>
          </td>
        <% end %>
        <td>
          <% issues_t = @issues.where(:tracker_id => tracker.id) %>
          <% results = get_time_statistics(issues_t, @intervention_time, @resolve_time, @intervention_status, @resolve_status) %>
          <% results.each do |result| %>
            <%= result %><br>
          <% end %>
        </td>
        <td>
          <% issues_t = @issues.where(:tracker_id => tracker.id) %>
          <% results = get_time_averages(issues_t, @intervention_time, @resolve_time, @intervention_status, @resolve_status) %>
          <% results.each do |result| %>
            <%= result %><br>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <th><%= l(:issuestats_all_trackers) %></th>
      <% @priorities.each do |priority| %>
        <td>
          <% issues_p = @issues.where(:priority_id => priority.id) %>
          <% results = get_time_statistics(issues_p, @intervention_time, @resolve_time, @intervention_status, @resolve_status) %>
          <% results.each do |result| %>
            <%= result %><br>
          <% end %>
        </td>
      <% end %>
      <td>
        <% results = get_time_statistics(@issues, @intervention_time, @resolve_time, @intervention_status, @resolve_status) %>
        <% results.each do |result| %>
          <%= result %><br>
        <% end %>
      </td>
      <td>
        <% results = get_time_averages(@issues, @intervention_time, @resolve_time, @intervention_status, @resolve_status) %>
        <% results.each do |result| %>
          <%= result %><br>
        <% end %>
      </td>
    </tr>
  </tr>
</table>

<br>
<h2><%= l(:issuestats_issue_details) %></h2>

<table border="1" width="100%">
  <thead>
    <tr>
      <th><%= l(:issuestats_issue_tracker_id) %></th>
      <th><%= l(:issuestats_issue_subject) %></th>
      <th><%= l(:issuestats_intervention_time_h) %></th>
      <th><%= l(:issuestats_resolve_time_h) %></th>
    </tr>
  </thead>

    <tr>
      <% @issues.each do |issue| %>
        <tr>
          <th><%= link_to Tracker.find(issue.tracker_id).name.to_s + " #" + issue.id.to_s, issue_path(issue) %></th>
          <td><%= issue.subject %></td>
          <td>
            <% int_time = get_issue_intervention_time(issue, @intervention_status) %>
            <% if int_time == (-1) %>
              <%= l(:issuestats_not_intervened) %>
            <% else %>
              <%= (int_time.to_f/60).round(2) %>
            <% end %>
          </td>
          <td>
            <% res_time = get_issue_resolve_time(issue, @intervention_status, @resolve_status) %>
            <% if res_time == (-1) %>
              <%= l(:issuestats_not_resolved) %>
            <% else %>
              <%= (res_time.to_f/60).round(2) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tr>

</table>